components:
  schemas:
    AP:
      properties:
        cid:
          title: CPE ID
          type: string
        client_script:
          title: Client script version
          type: string
        fw_version:
          title: Firmware version
          type: string
        interfaces:
          additionalProperties:
            $ref: '#/components/schemas/IfaceAddress'
          default: {}
          title: Interfaces
          type: object
        last_seen:
          format: date-time
          title: Last Seen Timestamp
          type: string
        mac:
          title: MAC Address
          type: string
        model:
          title: Model
          type: string
        name:
          title: Device Name
          type: string
        online_status:
          allOf:
          - $ref: '#/components/schemas/DeviceOnlineStatus'
          default: unknown
          title: Online Status
        powersave_status:
          title: Powersave Status
          type: boolean
        serial:
          title: Serial Number
          type: string
        updated_timestamp:
          format: date-time
          title: Updated Timestamp
          type: string
        uptime:
          title: Device uptime
          type: number
        zone_name:
          title: Zone Name
          type: string
      required:
      - mac
      title: AP
      type: object
    APIExceptionModel:
      properties:
        detail:
          title: Detail
          type: string
      required:
      - detail
      title: APIExceptionModel
      type: object
    CPE:
      properties:
        category:
          allOf:
          - $ref: '#/components/schemas/CPECategory'
          title: CPE Category
        cid:
          title: CPE ID
          type: string
        interfaces:
          additionalProperties:
            $ref: '#/components/schemas/IfaceAddress'
          default: {}
          title: Interfaces
          type: object
        last_seen:
          format: date-time
          title: Last Seen Timestamp
          type: string
        mac:
          title: MAC Address
          type: string
        model:
          title: Model
          type: string
        online_status:
          allOf:
          - $ref: '#/components/schemas/DeviceOnlineStatus'
          default: unknown
          title: Online Status
        serial:
          title: Serial Number
          type: string
        uplink_cid:
          title: Uplink CPE ID
          type: string
        uplink_mac:
          title: Uplink MAC Address
          type: string
      required:
      - mac
      - cid
      - category
      title: CPE
      type: object
    CPECategory:
      description: An enumeration.
      enum:
      - CPE-M
      - CPE-E
      - CPE-O
      - CPE-W
      title: CPECategory
      type: string
    CPEStatus:
      properties:
        indoor_cpe:
          allOf:
          - $ref: '#/components/schemas/CPE'
          title: Indoor CPE
        outdoor_cpe:
          allOf:
          - $ref: '#/components/schemas/CPE'
          title: Outdoor CPE
        uplink_bssid:
          title: Uplink BSSID
          type: string
      title: CPEStatus
      type: object
    CustomerSubscriptionInfo:
      properties:
        billing_township:
          default: na
          title: Billing Township
          type: string
        cpe_id:
          default: na
          title: Cpe Id
          type: string
        current_package:
          default: na
          title: Current Package
          type: string
        customer_id:
          default: na
          title: Customer Id
          type: string
        customerid:
          title: Customer ID
          type: string
        service_type:
          default: na
          title: Service Type
          type: string
        subscription_status:
          default: na
          title: Subscription Status
          type: string
      required:
      - customerid
      title: CustomerSubscriptionInfo
      type: object
    DeviceOnlineStatus:
      description: An enumeration.
      enum:
      - up
      - down
      - unknown
      title: DeviceOnlineStatus
      type: string
    FiberInfo:
      properties:
        device_mac:
          title: Device Mac
          type: string
        gpon_name:
          title: Gpon Name
          type: string
        hostname:
          title: Hostname
          type: string
        l1_splitter:
          title: L1 Splitter
          type: string
        l2_splitter:
          title: L2 Splitter
          type: string
        olt:
          $ref: '#/components/schemas/OLTInfo'
        otb:
          title: Otb
          type: string
        profile:
          title: Profile
          type: string
        profile_id:
          title: Profile Id
          type: string
        serial:
          title: Serial
          type: string
        status:
          $ref: '#/components/schemas/ONUStatus'
      required:
      - hostname
      - serial
      - device_mac
      - profile
      - gpon_name
      - profile_id
      title: FiberInfo
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    IfaceAddress:
      properties:
        cidr:
          format: ipv4interface
          title: IPv4 CIDR Address
          type: string
        ip:
          format: ipv4
          title: IPv4 Address
          type: string
        netmask:
          format: ipv4
          title: IPv4 Netmask
          type: string
      title: IfaceAddress
      type: object
    OLTInfo:
      properties:
        hostname:
          title: Hostname
          type: string
        last_seen:
          title: Last Seen
          type: string
        mac:
          title: Mac
          type: string
        mgmt_ip:
          title: Mgmt Ip
          type: string
        operational_status:
          title: Operational Status
          type: string
        status:
          anyOf:
          - type: integer
          - type: string
          title: Status
      required:
      - mac
      - hostname
      - mgmt_ip
      - operational_status
      title: OLTInfo
      type: object
    ONUStatus:
      properties:
        last_seen:
          title: Last Seen
          type: string
        phase_state:
          title: Phase State
          type: string
        signal:
          title: Signal
          type: string
        status:
          anyOf:
          - type: integer
          - type: string
          title: Status
        uptime:
          title: Uptime
          type: string
      required:
      - signal
      - phase_state
      title: ONUStatus
      type: object
    SubscriptionInfo:
      properties:
        cid:
          title: CPE ID
          type: string
        installation_type:
          default: na
          title: Installation Type
          type: string
        subscribed_plan:
          default: na
          title: Subscribed Plan
          type: string
        subscription_status:
          default: na
          title: Subscription Status
          type: string
      required:
      - cid
      title: SubscriptionInfo
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: cpe_lookup
  version: 1.2.0
openapi: 3.0.2
paths:
  /cpes/{cid}/status:
    get:
      description: Get CPE technical information and online status.
      operationId: get_cpe_status_cpes__cid__status_get
      parameters:
      - in: path
        name: cid
        required: true
        schema:
          title: Cid
          type: string
      - in: query
        name: check_realtime
        required: false
        schema:
          default: false
          title: Check Realtime
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CPEStatus'
          description: CPE device information and online status
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIExceptionModel'
          description: CPE not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
        '503':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIExceptionModel'
          description: Service or upstream unavailable temporarily
      summary: Get device status for both indoor and outdoor CPEs
      tags:
      - cpe-info
  /cpes/{cid}/subscriptions/internet:
    get:
      operationId: cpe_subscription_cpes__cid__subscriptions_internet_get
      parameters:
      - in: path
        name: cid
        required: true
        schema:
          title: Cid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionInfo'
          description: Service subscription associated with the CPE and type of installation
            provided.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get CPE Plan and Installation Type
      tags:
      - subscription-info
  /customers/{customerid}/subscription:
    get:
      operationId: customer_subscription_info_customers__customerid__subscription_get
      parameters:
      - in: path
        name: customerid
        required: true
        schema:
          title: Customerid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerSubscriptionInfo'
          description: CPE ID and subscription status
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get cpe id and subscription status
      tags:
      - customer_subscription-info
  /healthcheck:
    get:
      operationId: healthcheck_healthcheck_get
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: Successful Response
      summary: Healthcheck
      tags:
      - internal-routes
  /server_info:
    get:
      operationId: server_info_server_info_get
      responses:
        '200':
          content:
            text/plain:
              example: cpe_lookup/0.1.0
              schema:
                type: string
          description: Application name and version
      summary: Server Info
      tags:
      - internal-routes
  /tickets/cpe/{cid}/assetinfo:
    get:
      operationId: assetinfo_tickets_cpe__cid__assetinfo_get
      parameters:
      - in: path
        name: cid
        required: true
        schema:
          title: Cid
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Asset informations associated with the CPE
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get asset info of CPE
      tags:
      - ticket-info
  /tickets/cpe/{cid}/tktinfo:
    get:
      operationId: ticketinfo_tickets_cpe__cid__tktinfo_get
      parameters:
      - in: path
        name: cid
        required: true
        schema:
          title: Cid
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Ticket informations associated with the CPE
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get TKT info of CPE
      tags:
      - ticket-info
  /uplink/fiber/{cid}/status:
    get:
      operationId: fiber_uplink_uplink_fiber__cid__status_get
      parameters:
      - in: path
        name: cid
        required: true
        schema:
          title: Cid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FiberInfo'
          description: Uplink ONU and OLT informations associated with the CPE are
            provided.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get fiber uplink info
      tags:
      - fiber-uplink-info
  /uplink/wireless/{bssid}/status:
    get:
      description: Get AP technical information and online status.
      operationId: get_ap_status_uplink_wireless__bssid__status_get
      parameters:
      - in: path
        name: bssid
        required: true
        schema:
          title: Bssid
      - in: query
        name: check_realtime
        required: false
        schema:
          default: false
          title: Check Realtime
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AP'
          description: AP device information and online status
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIExceptionModel'
          description: AP not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
        '503':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIExceptionModel'
          description: Service or upstream unavailable temporarily
      summary: Get wireless uplink AP status for both Ruckus and Frontiir AP
      tags:
      - ap-info
tags:
- description: Endpoints for internal operations such as active healthchecking from
    control-plane.
  name: internal-routes
- description: Endpoints for retrieving CPE subscription and service information from
    business systems.
  name: subscription-info
- description: Endpoints for retrieving CPE device information from CPEMS
  name: cpe-info
- description: Endpoints for retrieving CPE ID and subscription plan status from business
    systems.
  name: customer-info
- description: Endpoints for retrieving Access Point information from OSS API.
  name: ap-info
- description: Endpoints for retrieving ticket informations and asset informations
    from Request Tracker(RT).
  name: ticket-info
